# See example at: https://github.com/avto-dev/markdown-lint/blob/master/lint/config/changelog.yml

# Line length <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013>
# XXX Temporary disabled because of line continuation edge-case. See:
# https://github.com/DavidAnson/markdownlint/issues/302
MD013: false

# Inline HTML <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033>
# is allowed for beautiful rendering on GitHub.
MD033:
  # Whitelist some elements for beautiful rendering on GitHub.
  allowed_elements:
    - 'img'
