---
name: Autofix
"on":
  push:
    # Only targets default branch to avoid amplification effects of
    # auto-fixing the exact same stuff in multiple non-rebased branches.
    branches:
      - 'main'
  schedule:
    # Run linter every week to catch regressions from external dependencies.
    - cron: 17 9 * * 1

jobs:

  toc:
    name: Generator TOC and auto-commit
    runs-on: ubuntu-20.04
    steps:
      - name: Install doctoc
        run: |
          sudo npm install -g doctoc
      - uses: actions/checkout@v2.3.4
      - name: Generate full TOC
        run: |
          doctoc --github readme.md
      - name: Remove forbidden special TOC entries
        # See: https://github.com/sindresorhus/awesome-lint/blob/v0.16.0/rules
        # /toc.js#L15-L18
        run: >
          gawk -i inplace '!/^- \[(Contributing|Footnotes)\]\(#.+\)$/{print}'
          ./readme.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_author: "Kevin Deldycke <kevin@deldycke.com>"
          commit_message: "[lint] Update TOC."
          file_pattern: readme.md

  typos:
    name: Fix typos and create a PR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: sobolevn/misspell-fixer-action@0.1.0
      - uses: peter-evans/create-pull-request@v3
        with:
          author: "Kevin Deldycke <kevin@deldycke.com>"
          commit-message: "Fix typo."
          title: "Typo"
          body: >
            [Auto-generated on run #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            as defined by [workflow action](https://github.com/${{ github.repository }}/blob/${{ github.base_ref }}/.github/workflows/autofix.yaml).
          labels: "typo"
          assignees: kdeldycke
          branch: fix-typo
