name: Sync labels
on:
  push:
    # Only targets default branch to avoid amplification effects of
    # doing the exact same stuff in multiple non-rebased branches.
    branches:
      - 'master'

jobs:

  sync_labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: lannonbr/issue-label-manager-action@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
